// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANqNL14Y1__BZ-ZlIsiaHO-kGnX2E9L74',
    appId: '1:8953158348:web:acb7333f109f6d0b3a0069',
    messagingSenderId: '8953158348',
    projectId: 'firstproject-2d191',
    authDomain: 'firstproject-2d191.firebaseapp.com',
    storageBucket: 'firstproject-2d191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmGlbgz2LaXD33Neak0A4zsEI0uFO2ug',
    appId: '1:8953158348:android:320aee113854110c3a0069',
    messagingSenderId: '8953158348',
    projectId: 'firstproject-2d191',
    storageBucket: 'firstproject-2d191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKSsgpEImS2EOQW3kVqwlIQpWjzpQrjc',
    appId: '1:8953158348:ios:18c0872e38fcf45e3a0069',
    messagingSenderId: '8953158348',
    projectId: 'firstproject-2d191',
    storageBucket: 'firstproject-2d191.firebasestorage.app',
    iosBundleId: 'com.example.session12Ass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKSsgpEImS2EOQW3kVqwlIQpWjzpQrjc',
    appId: '1:8953158348:ios:18c0872e38fcf45e3a0069',
    messagingSenderId: '8953158348',
    projectId: 'firstproject-2d191',
    storageBucket: 'firstproject-2d191.firebasestorage.app',
    iosBundleId: 'com.example.session12Ass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANqNL14Y1__BZ-ZlIsiaHO-kGnX2E9L74',
    appId: '1:8953158348:web:0c2e53846c9039463a0069',
    messagingSenderId: '8953158348',
    projectId: 'firstproject-2d191',
    authDomain: 'firstproject-2d191.firebaseapp.com',
    storageBucket: 'firstproject-2d191.firebasestorage.app',
  );
}
